%% Set figure properties for all plots in the project. 
% Just run this script in any script with plots to standardize formatting
% features across plots.

% Default figure properties
set(0,...
    'DefaultFigureColor', [1 1 1],...
    'DefaultAxesFontSize', 12, ...
    'DefaultAxesBox', 'off', ...
    'DefaultLineMarkerSize', 8, ...
    'DefaultAxesFontName','Times New Roman', ...
    'DefaultTextInterpreter','Latex', ...
    'DefaultAxesLineWidth', 1,...               
    'DefaultLegendFontSize', 12, ...             
    'DefaultLegendBox', 'off')
